#
###################################
# Site wide configuration
####################################
#
title: Shengan Zhang
email: zshengan@umich.edu
description: Computer Science, Class of 2020
url: https://shenganzhang.github.io
keywords: ["Sheng'an", "Zhang", "Shengan"]

#
###################################
# Jekyll configuration
####################################
#
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Shengan Zhang"
  avatar: logo.png
  job: "Computer Science, Class of 2021"
  bio: "College of Engineering, University of Michigan, Ann Arbor"
  email: zshengan@umich.edu
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: shenganzhang
  gitlab:
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
